import type { createApiClient } from '@/lib/api';

type ApiClient = ReturnType<typeof createApiClient>;

const VAPID_PUBLIC_KEY = process.env.EXPO_PUBLIC_VAPID_PUBLIC_KEY ?? '';

export function isPushSupported(): boolean {
  return (
    typeof navigator !== 'undefined' &&
    'serviceWorker' in navigator &&
    typeof window !== 'undefined' &&
    'PushManager' in window &&
    'Notification' in window &&
    VAPID_PUBLIC_KEY !== ''
  );
}

// Converts the VAPID public key — base64url, no padding, as generated by
// webpush.GenerateVAPIDKeys() — into the raw bytes pushManager.subscribe
// expects for applicationServerKey. Cast to BufferSource: TS's DOM lib types
// Uint8Array.buffer as ArrayBufferLike, which isn't assignable to the
// ArrayBuffer-typed BufferSource subscribe() expects, even though the value
// itself is a plain ArrayBuffer at runtime.
function urlBase64ToUint8Array(base64Url: string): BufferSource {
  const padding = '='.repeat((4 - (base64Url.length % 4)) % 4);
  const base64 = (base64Url + padding).replace(/-/g, '+').replace(/_/g, '/');
  const raw = atob(base64);
  return Uint8Array.from([...raw].map((c) => c.charCodeAt(0))) as BufferSource;
}

function subscriptionToPayload(sub: PushSubscription) {
  const json = sub.toJSON();
  return {
    endpoint: json.endpoint ?? '',
    p256dh: json.keys?.p256dh ?? '',
    auth: json.keys?.auth ?? '',
  };
}

async function getOrCreateSubscription(): Promise<PushSubscription | null> {
  const registration = await navigator.serviceWorker.ready;
  const existing = await registration.pushManager.getSubscription();
  if (existing) return existing;
  return registration.pushManager.subscribe({
    userVisibleOnly: true,
    applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY),
  });
}

// Shows the browser's permission prompt and, if granted, subscribes this
// device and registers it with the backend. Returns whether push ended up
// enabled — callers use this to decide whether to also PATCH the server-side
// preference.
export async function requestPermissionAndSubscribe(api: ApiClient): Promise<boolean> {
  if (!isPushSupported()) return false;

  const permission = await Notification.requestPermission();
  if (permission !== 'granted') return false;

  const sub = await getOrCreateSubscription();
  if (!sub) return false;

  await api.post('/api/v1/push/subscribe', subscriptionToPayload(sub));
  return true;
}

// Called on app boot. If the user already granted browser permission and has
// push enabled server-side, (re-)registers this browser/device — never
// prompts, since the permission dialog only shows once per site and firing
// it unprompted isn't possible anyway. Always re-POSTs the subscription to
// the backend even if the browser already has one cached: /push/subscribe is
// a cheap upsert (unique on user_id+endpoint), and re-sending it is what lets
// a device recover if the backend's record was ever lost (e.g. a database
// reset) without the browser-side PushSubscription object — which is what
// getSubscription() below checks — knowing anything changed.
export async function ensureSubscribed(api: ApiClient): Promise<void> {
  if (!isPushSupported()) return;
  if (typeof Notification === 'undefined' || Notification.permission !== 'granted') return;

  try {
    const me = await api.get<{ push_enabled: boolean }>('/api/v1/users/me');
    if (!me.push_enabled) return;

    const sub = await getOrCreateSubscription();
    if (!sub) return;
    await api.post('/api/v1/push/subscribe', subscriptionToPayload(sub));
  } catch {
    // Best-effort — a failure here shouldn't disrupt app boot.
  }
}
