import { File, Paths } from 'expo-file-system';
import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import * as Sharing from 'expo-sharing';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Platform, Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import Swipeable from 'react-native-gesture-handler/ReanimatedSwipeable';
import { SafeAreaView } from 'react-native-safe-area-context';

import { Avatar } from '@/components/avatar';
import { BackButton } from '@/components/back-button';
import { BottomNav } from '@/components/bottom-nav';
import { ConfirmDialog } from '@/components/confirm-dialog';
import { CategoryChart } from '@/components/category-chart';
import { EditGroupIconModal } from '@/components/edit-group-icon-modal';
import { EditGroupNameModal } from '@/components/edit-group-name-modal';
import { Icon } from '@/components/icon';
import {
  FilterBadgeButton,
  FilterChipRow,
  FilterSection,
  FilterSegment,
  FilterSheet,
  type FilterChipOption,
} from '@/components/filter-sheet';
import { OfflineBanner } from '@/components/offline-banner';
import { ScreenMeta } from '@/components/screen-meta';
import { CATEGORIES, categoryColor, categoryIcon } from '@/constants/categories';
import { Font, Radius, TILE_ICON_COLOR, avatarColor, groupIcon, tileBg, type ThemeColors } from '@/constants/design';
import { useAuth } from '@/lib/auth';
import { periodCutoff, type PeriodFilter } from '@/lib/date-filter';
import { formatAmount, i18n, t } from '@/lib/i18n';
import { rememberLastGroup } from '@/lib/last-group';
import { cacheData, getCachedData } from '@/lib/offline-cache';
import { getPendingExpenses, syncPendingExpenses, type PendingExpense } from '@/lib/offline-queue';
import { useColors } from '@/lib/settings';

export type Group = {
  id: number;
  name: string;
  emoji: string;
  currency: string;
  members: { id: number; name: string; avatar_url?: string | null }[];
};

type ExpenseItem = {
  id: number;
  description: string;
  amount: number;
  users: { id: number; name: string; avatar_url?: string | null }[];
};

export type Expense = {
  id: number;
  description: string;
  category: string;
  amount: number;
  paid_by: { id: number; name: string };
  splits: { user_id: number; amount: number }[];
  items?: ExpenseItem[];
  created_at: string;
  // Only present on the single-expense fetch (GetExpense), never on the
  // group's expense list — a fresh short-lived signed URL, generated by the
  // backend on each request.
  receipt_image_url?: string;
  // Soft-deleted expenses are still returned by the group's expense list (not
  // excluded like everywhere else) so history can show them struck through
  // instead of just vanishing. null/absent means still active.
  deleted_at?: string | null;
  deleted_by?: { id: number; name: string } | null;
};

export type Settlement = {
  id: number;
  from_user_id: number;
  to_user_id: number;
  amount: number;
  created_at: string;
  // Embedded by the backend on the single-settlement and group-list
  // endpoints (not on the activity feed, which only has ids/amounts).
  from_user?: { id: number; name: string; avatar_url?: string | null };
  to_user?: { id: number; name: string; avatar_url?: string | null };
};

type Debt = { from_user_id: number; to_user_id: number; amount: number };

type HistoryItem =
  | { kind: 'expense'; date: string; expense: Expense }
  | { kind: 'payment'; date: string; settlement: Settlement }
  | { kind: 'pending'; date: string; pending: PendingExpense };

type GroupSnapshot = { group: Group; expenses: Expense[]; settlements: Settlement[]; debts: Debt[] };

function ordinalSuffix(day: number): string {
  if (day >= 11 && day <= 13) return 'th';
  switch (day % 10) {
    case 1:
      return 'st';
    case 2:
      return 'nd';
    case 3:
      return 'rd';
    default:
      return 'th';
  }
}

// "4th July" (en) / "4 de julio" (es) — Spanish dates don't use ordinals the
// way English ones do, so the two locales get genuinely different shapes
// rather than just a translated month name.
function longDate(iso: string): string {
  const d = new Date(iso);
  if (isNaN(d.getTime())) return '';
  if (i18n.locale === 'es') {
    return new Intl.DateTimeFormat('es-AR', { day: 'numeric', month: 'long' }).format(d);
  }
  const month = new Intl.DateTimeFormat('en-US', { month: 'long' }).format(d);
  return `${d.getDate()}${ordinalSuffix(d.getDate())} ${month}`;
}

export default function GroupDetailScreen() {
  const { id, tab: tabParam } = useLocalSearchParams<{ id: string; tab?: string }>();
  const { api } = useAuth();
  const Palette = useColors();
  const styles = useMemo(() => makeStyles(Palette), [Palette]);

  const [group, setGroup] = useState<Group | null>(null);
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [settlements, setSettlements] = useState<Settlement[]>([]);
  const [debts, setDebts] = useState<Debt[]>([]);
  const [myId, setMyId] = useState<number | null>(null);
  // A shortcut can deep-link straight to the balances tab (?tab=balances);
  // any other/missing value falls back to the default history view.
  const [tab, setTab] = useState<'history' | 'balances' | 'stats'>(
    tabParam === 'balances' ? 'balances' : 'history',
  );
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [inviteUrl, setInviteUrl] = useState<string | null>(null);
  const [exportingCsv, setExportingCsv] = useState(false);
  const [deletingSettlementId, setDeletingSettlementId] = useState<number | null>(null);
  const [deletingSettlement, setDeletingSettlement] = useState(false);
  const [deletingExpenseId, setDeletingExpenseId] = useState<number | null>(null);
  const [deletingExpense, setDeletingExpense] = useState(false);
  const [pending, setPending] = useState<PendingExpense[]>([]);
  const [editingIcon, setEditingIcon] = useState(false);
  const [editingName, setEditingName] = useState(false);
  const [savingGroup, setSavingGroup] = useState(false);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [filterType, setFilterType] = useState<'all' | 'expense' | 'settlement'>('all');
  const [filterPeriod, setFilterPeriod] = useState<PeriodFilter>('all');
  const [filterCategory, setFilterCategory] = useState<string | null>(null);
  const [filterUserId, setFilterUserId] = useState<number | null>(null);
  // Lets the sync-then-reload step below call the latest `load` without
  // referencing the `load` const from inside its own definition.
  const loadRef = useRef<() => void>(() => {});

  const load = useCallback(() => {
    if (!id) return;
    setLoading(true);
    setError(null);
    Promise.all([
      api.get<Group>(`/api/v1/groups/${id}`),
      api.get<Expense[]>(`/api/v1/groups/${id}/expenses`),
      api.get<Settlement[]>(`/api/v1/groups/${id}/settlements`),
      api.get<Debt[]>(`/api/v1/groups/${id}/balances`),
      api.get<{ id: number }>('/api/v1/users/me'),
    ])
      .then(([g, ex, st, d, me]) => {
        setGroup(g);
        setExpenses(ex ?? []);
        setSettlements(st ?? []);
        setDebts(d ?? []);
        setMyId(me.id);
        rememberLastGroup(g.id);
        cacheData(`group-${id}`, { group: g, expenses: ex ?? [], settlements: st ?? [], debts: d ?? [] });
        cacheData('me', me);
        // We're online (the fetches above just succeeded) — flush anything
        // queued for this group and reload once more if something synced,
        // so it moves from "Pending" to a real, server-confirmed row.
        syncPendingExpenses(api).then((synced) => {
          if (synced > 0) loadRef.current();
          else getPendingExpenses(Number(id)).then(setPending);
        });
      })
      .catch(async () => {
        const cached = await getCachedData<GroupSnapshot>(`group-${id}`);
        if (cached) {
          setGroup(cached.data.group);
          setExpenses(cached.data.expenses);
          setSettlements(cached.data.settlements);
          setDebts(cached.data.debts);
          const me = await getCachedData<{ id: number }>('me');
          if (me) setMyId(me.data.id);
        } else {
          setError(t('groupDetail.loadError'));
        }
        getPendingExpenses(Number(id)).then(setPending);
      })
      .finally(() => setLoading(false));
  }, [id, api]);

  useEffect(() => {
    loadRef.current = load;
  }, [load]);

  useFocusEffect(load);

  // Preload the invite link so the copy button can write to the clipboard
  // synchronously on click — Safari rejects clipboard writes that happen after
  // an awaited fetch, since the user gesture is considered consumed.
  useFocusEffect(
    useCallback(() => {
      if (!id) return;
      api
        .get<{ url: string }>(`/api/v1/groups/${id}/invite`)
        .then(({ url }) => setInviteUrl(url))
        .catch(() => {});
    }, [id, api]),
  );

  // Auto-dismiss the error toast.
  useEffect(() => {
    if (!errorMsg) return;
    const timer = setTimeout(() => setErrorMsg(null), 2600);
    return () => clearTimeout(timer);
  }, [errorMsg]);

  // Briefly show the copied tick on the share button.
  useEffect(() => {
    if (!copied) return;
    const timer = setTimeout(() => setCopied(false), 1600);
    return () => clearTimeout(timer);
  }, [copied]);

  const memberName = useCallback(
    (uid: number) =>
      group?.members.find((m) => m.id === uid)?.name ?? t('groupDetail.userN', { id: uid }),
    [group],
  );

  const memberAvatar = useCallback(
    (uid: number) => group?.members.find((m) => m.id === uid)?.avatar_url ?? '',
    [group],
  );

  // Unified history: expenses, payments, and not-yet-synced expenses
  // (queued while offline) interleaved, newest first.
  const history = useMemo<HistoryItem[]>(() => {
    const items: HistoryItem[] = [
      ...expenses.map((e) => ({ kind: 'expense' as const, date: e.created_at, expense: e })),
      ...settlements.map((s) => ({ kind: 'payment' as const, date: s.created_at, settlement: s })),
      ...pending.map((p) => ({ kind: 'pending' as const, date: p.createdAt, pending: p })),
    ];
    return items.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
  }, [expenses, settlements, pending]);

  // Filter option lists are derived from this group's own activity — no
  // "Group" dimension here since we're already inside one.
  const categoryOptions = useMemo(() => {
    const present = new Set(expenses.filter((e) => !e.deleted_at).map((e) => e.category).filter(Boolean));
    return CATEGORIES.filter((c) => present.has(c.slug));
  }, [expenses]);

  const userOptions = useMemo(() => {
    const map = new Map<number, string>();
    expenses.filter((e) => !e.deleted_at).forEach((e) => map.set(e.paid_by.id, e.paid_by.name));
    settlements.forEach((s) => map.set(s.from_user_id, memberName(s.from_user_id)));
    pending.forEach((p) => {
      const member = group?.members.find((m) => m.id === p.payload.paid_by_id);
      if (member) map.set(member.id, member.name);
    });
    return [...map.entries()].map(([uid, name]) => ({ id: uid, name })).sort((a, b) => a.name.localeCompare(b.name));
  }, [expenses, settlements, pending, group, memberName]);

  const filteredHistory = useMemo(() => {
    const cutoff = periodCutoff(filterPeriod);
    return history.filter((item) => {
      if (cutoff && new Date(item.date) < cutoff) return false;
      if (item.kind === 'pending') {
        if (filterType === 'settlement') return false;
        if (filterCategory != null && item.pending.payload.category !== filterCategory) return false;
        if (filterUserId != null && item.pending.payload.paid_by_id !== filterUserId) return false;
        return true;
      }
      if (item.kind === 'payment') {
        if (filterType === 'expense') return false;
        if (filterCategory != null) return false;
        if (filterUserId != null && item.settlement.from_user_id !== filterUserId) return false;
        return true;
      }
      if (filterType === 'settlement') return false;
      if (filterCategory != null && item.expense.category !== filterCategory) return false;
      if (filterUserId != null && item.expense.paid_by.id !== filterUserId) return false;
      return true;
    });
  }, [history, filterType, filterPeriod, filterCategory, filterUserId]);

  const activeFilterCount = [
    filterType !== 'all',
    filterPeriod !== 'all',
    filterCategory != null,
    filterUserId != null,
  ].filter(Boolean).length;

  const clearFilters = () => {
    setFilterType('all');
    setFilterPeriod('all');
    setFilterCategory(null);
    setFilterUserId(null);
  };

  // Total group spend per category (settlements aren't spending, so they're
  // excluded), largest first — powers the spending chart.
  const categoryBreakdown = useMemo(() => {
    const totals = new Map<string, number>();
    for (const e of expenses) {
      if (e.deleted_at) continue;
      const slug = e.category || 'other';
      totals.set(slug, (totals.get(slug) ?? 0) + e.amount);
    }
    const slices = [...totals.entries()]
      .map(([slug, amount]) => ({ slug, amount }))
      .sort((a, b) => b.amount - a.amount);
    const total = slices.reduce((sum, s) => sum + s.amount, 0);
    return { slices, total };
  }, [expenses]);

  const handleShare = useCallback(async () => {
    let url = inviteUrl;
    if (!url) {
      try {
        url = (await api.get<{ url: string }>(`/api/v1/groups/${id}/invite`)).url;
      } catch {
        setErrorMsg(t('groupDetail.shareError'));
        return;
      }
    }
    if (Platform.OS === 'web') {
      // Copy straight to the clipboard instead of opening the OS share sheet.
      try {
        await navigator.clipboard.writeText(url);
        setCopied(true);
      } catch {
        setErrorMsg(t('groupDetail.copyError'));
      }
    } else {
      Share.share({ message: url }).catch(() => {});
    }
  }, [api, id, inviteUrl]);

  const handleExportCsv = useCallback(async () => {
    if (exportingCsv) return;
    setExportingCsv(true);
    try {
      const { blob, filename } = await api.getBlob(`/api/v1/groups/${id}/export.csv`);
      if (Platform.OS === 'web') {
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        a.remove();
        URL.revokeObjectURL(url);
      } else {
        const file = new File(Paths.cache, filename);
        file.create({ overwrite: true });
        file.write(await blob.text());
        await Sharing.shareAsync(file.uri, { mimeType: 'text/csv', dialogTitle: filename });
      }
    } catch {
      setErrorMsg(t('groupDetail.exportError'));
    } finally {
      setExportingCsv(false);
    }
  }, [api, id, exportingCsv]);

  const confirmDeleteSettlement = useCallback(async () => {
    if (deletingSettlementId == null || deletingSettlement) return;
    setDeletingSettlement(true);
    try {
      await api.delete(`/api/v1/settlements/${deletingSettlementId}`);
      setDeletingSettlementId(null);
      load();
    } catch {
      setDeletingSettlementId(null);
      setErrorMsg(t('groupDetail.deleteSettlementError'));
    } finally {
      setDeletingSettlement(false);
    }
  }, [api, deletingSettlementId, deletingSettlement, load]);

  const confirmDeleteExpense = useCallback(async () => {
    if (deletingExpenseId == null || deletingExpense) return;
    setDeletingExpense(true);
    try {
      await api.delete(`/api/v1/expenses/${deletingExpenseId}`);
      setDeletingExpenseId(null);
      load();
    } catch {
      setDeletingExpenseId(null);
      setErrorMsg(t('expenseDetail.deleteError'));
    } finally {
      setDeletingExpense(false);
    }
  }, [api, deletingExpenseId, deletingExpense, load]);

  const saveIcon = useCallback(
    async (emoji: string) => {
      if (savingGroup) return;
      setEditingIcon(false);
      if (emoji === group?.emoji) return;
      setSavingGroup(true);
      try {
        const updated = await api.patch<Group>(`/api/v1/groups/${id}`, { emoji });
        setGroup(updated);
      } catch {
        setErrorMsg(t('groupDetail.editError'));
      } finally {
        setSavingGroup(false);
      }
    },
    [api, id, group, savingGroup],
  );

  const saveName = useCallback(
    async (name: string) => {
      if (!name.trim() || savingGroup) return;
      setSavingGroup(true);
      try {
        const updated = await api.patch<Group>(`/api/v1/groups/${id}`, { name: name.trim() });
        setGroup(updated);
        setEditingName(false);
      } catch {
        setErrorMsg(t('groupDetail.editError'));
      } finally {
        setSavingGroup(false);
      }
    },
    [api, id, savingGroup],
  );

  if (loading && !group) {
    return (
      <View style={styles.root}>
        <ScreenMeta title={t('groupDetail.title')} />
        <SafeAreaView edges={['top']} style={styles.center}>
          <ActivityIndicator color={Palette.green} />
        </SafeAreaView>
      </View>
    );
  }
  if (error || !group) {
    return (
      <View style={styles.root}>
        <ScreenMeta title={t('groupDetail.title')} />
        <SafeAreaView edges={['top']} style={styles.center}>
          <Text style={styles.muted}>{error ?? t('groupDetail.notFound')}</Text>
        </SafeAreaView>
      </View>
    );
  }

  // My net in this group, derived from simplified debts.
  let myNet = 0;
  for (const d of debts) {
    if (d.to_user_id === myId) myNet += d.amount;
    if (d.from_user_id === myId) myNet -= d.amount;
  }
  const owed = myNet > 0;
  const owe = myNet < 0;
  const summaryColor = owed ? Palette.green : owe ? Palette.red : Palette.muted;
  const summaryWord = owed
    ? t('groupDetail.wordOwed')
    : owe
      ? t('groupDetail.wordOwe')
      : t('groupDetail.wordSettled');

  return (
    <View style={styles.root}>
      <ScreenMeta title={group.name} />
      <OfflineBanner pendingCount={pending.length} />
      <SafeAreaView edges={['top']} style={styles.safe}>
        {/* top bar */}
        <View style={styles.topbar}>
          <BackButton onPress={() => router.back()} />
          <View style={styles.topActions}>
            <Pressable
              onPress={handleExportCsv}
              disabled={exportingCsv}
              style={styles.iconBtn}
              accessibilityLabel={t('groupDetail.exportCsv')}>
              {exportingCsv ? (
                <ActivityIndicator color={Palette.ink} size="small" />
              ) : (
                <Icon name="download" size={20} color={Palette.ink} />
              )}
            </Pressable>
            <Pressable
              onPress={handleShare}
              style={styles.iconBtn}
              accessibilityLabel={t('groupDetail.copyLink')}>
              {copied ? (
                <Icon name="check" size={20} color={Palette.green} />
              ) : (
                <Icon name="copy" size={20} color={Palette.ink} />
              )}
            </Pressable>
          </View>
        </View>

        <ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
          {/* group header */}
          <View style={styles.groupHead}>
            <Pressable
              onPress={() => setEditingIcon(true)}
              style={[styles.tile, { backgroundColor: tileBg(group.id) }]}>
              <Icon name={groupIcon(group.emoji)} size={24} color={TILE_ICON_COLOR} />
            </Pressable>
            <View style={{ flex: 1 }}>
              <Pressable onPress={() => setEditingName(true)} style={styles.groupNameWrap}>
                <Text style={styles.groupName}>{group.name}</Text>
              </Pressable>
              <Text style={styles.groupMeta}>
                {t('groupDetail.memberCount', { count: group.members.length })}
              </Text>
            </View>
          </View>

          {/* balance summary */}
          <View
            style={[
              styles.summary,
              {
                backgroundColor: owe ? '#FBEEEC' : owed ? Palette.greenTint : Palette.card,
                borderColor: owe ? '#F0D6D2' : owed ? Palette.greenTintBorder : Palette.cardBorder,
              },
            ]}>
            <Text style={styles.summaryLabel}>{t('groupDetail.yourBalance')}</Text>
            <Text style={[styles.summaryAmount, { color: summaryColor }]}>
              {formatAmount(Math.abs(myNet), group.currency)}
            </Text>
            <Text style={[styles.summaryWord, { color: summaryColor }]}>{summaryWord}</Text>
          </View>

          {/* tabs */}
          <View style={styles.tabs}>
            <Pressable
              onPress={() => setTab('history')}
              style={[styles.tab, tab === 'history' && styles.tabActive]}>
              <Text style={[styles.tabText, tab === 'history' && styles.tabTextActive]}>
                {t('groupDetail.history')}
              </Text>
            </Pressable>
            <Pressable
              onPress={() => setTab('balances')}
              style={[styles.tab, tab === 'balances' && styles.tabActive]}>
              <Text style={[styles.tabText, tab === 'balances' && styles.tabTextActive]}>
                {t('groupDetail.balances')}
              </Text>
            </Pressable>
            <Pressable
              onPress={() => setTab('stats')}
              style={[styles.tab, tab === 'stats' && styles.tabActive]}>
              <Text style={[styles.tabText, tab === 'stats' && styles.tabTextActive]}>
                {t('groupDetail.spending')}
              </Text>
            </Pressable>
          </View>

          {tab === 'history' && (
            <>
              <View style={styles.filtersRow}>
                <FilterBadgeButton
                  label={t('activity.filters')}
                  count={activeFilterCount}
                  onPress={() => setFiltersOpen(true)}
                />
              </View>
              <View style={styles.list}>
                {history.length === 0 && <Text style={styles.muted}>{t('groupDetail.historyEmpty')}</Text>}
                {expenses.length === 0 && settlements.length === 0 && (
                  <Pressable
                    onPress={() => router.push(`/groups/${id}/import`)}
                    style={styles.importCta}>
                    <Text style={styles.importCtaText}>{t('groupDetail.importCta')}</Text>
                  </Pressable>
                )}
                {history.length > 0 && filteredHistory.length === 0 && (
                  <Text style={styles.muted}>{t('activity.noMatches')}</Text>
                )}
                {filteredHistory.map((item) => {
                if (item.kind === 'pending') {
                  const p = item.pending;
                  const icon = categoryIcon(p.payload.category);
                  const color = categoryColor(p.payload.category);
                  return (
                    <View key={`p${p.localId}`} style={styles.expenseCard}>
                      <View style={[styles.smallAvatar, { backgroundColor: `${color}26` }]}>
                        <Icon name={icon} size={18} color={color} />
                      </View>
                      <View style={{ flex: 1, minWidth: 0 }}>
                        <Text style={styles.expenseDesc} numberOfLines={1}>
                          {p.payload.description}
                        </Text>
                        <Text style={styles.pendingTag}>{t('groupDetail.pendingTag')}</Text>
                      </View>
                      <Text style={styles.expenseAmount}>
                        {formatAmount(p.payload.amount, group.currency)}
                      </Text>
                    </View>
                  );
                }
                if (item.kind === 'payment') {
                  const s = item.settlement;
                  const canDelete = myId != null && (s.from_user_id === myId || s.to_user_id === myId);
                  const card = (
                    <Pressable
                      onPress={() =>
                        router.push({
                          pathname: '/groups/[id]/settlement-detail',
                          params: { id: id as string, settlement: JSON.stringify(s), myId: String(myId ?? '') },
                        })
                      }
                      style={({ pressed }) => [styles.expenseCard, pressed && styles.pressed]}>
                      <View style={[styles.smallAvatar, { backgroundColor: `${Palette.green}26` }]}>
                        <Icon name="cash" size={18} color={Palette.green} />
                      </View>
                      <View style={{ flex: 1, minWidth: 0 }}>
                        <Text style={styles.expenseDesc} numberOfLines={1}>
                          {t('groupDetail.paymentTitle')}
                        </Text>
                        <Text style={styles.expenseMeta} numberOfLines={1}>
                          {t('groupDetail.paidFromTo', {
                            from: memberName(s.from_user_id),
                            to: memberName(s.to_user_id),
                            date: longDate(s.created_at),
                          })}
                        </Text>
                      </View>
                      <View style={{ alignItems: 'flex-end' }}>
                        <Text style={[styles.expenseAmount, { color: Palette.green }]}>
                          {formatAmount(s.amount, group.currency)}
                        </Text>
                      </View>
                    </Pressable>
                  );

                  // Only a party to the payment can delete it (mirrors the
                  // backend) — swipe is simply not offered to a bystander's
                  // row rather than dead-ending into a 403.
                  if (!canDelete) {
                    return <View key={`s${s.id}`}>{card}</View>;
                  }

                  return (
                    <Swipeable
                      key={`s${s.id}`}
                      overshootRight={false}
                      renderRightActions={(_progress, _translation, swipeableMethods) => (
                        <Pressable
                          onPress={() => {
                            swipeableMethods.close();
                            setDeletingSettlementId(s.id);
                          }}
                          style={styles.deleteAction}>
                          <Text style={styles.deleteActionText}>{t('common.delete')}</Text>
                        </Pressable>
                      )}>
                      {card}
                    </Swipeable>
                  );
                }
                const ex = item.expense;
                const isDeleted = !!ex.deleted_at;
                const myShare = ex.splits?.find((s) => s.user_id === myId)?.amount ?? 0;
                const paidByMe = ex.paid_by.id === myId;
                // When I paid, the useful number is what others owe me (total minus
                // my own share); otherwise it's what I owe.
                const lent = ex.amount - myShare;
                const icon = categoryIcon(ex.category);
                const iconColor = categoryColor(ex.category);
                // Mirrors the backend's own rule (isPayerOrSplitParticipant):
                // only the payer or a split participant may delete it. A
                // deleted expense is never re-deletable, but it does still
                // open — read-only — so the group can check what it was for.
                const canDeleteExpense =
                  !isDeleted && myId != null && (paidByMe || (ex.splits ?? []).some((s) => s.user_id === myId));
                const expenseCard = (
                  <Pressable
                    onPress={() =>
                      router.push({
                        pathname: '/groups/[id]/expense-detail',
                        params: { id: id as string, expense: JSON.stringify(ex), myId: String(myId ?? '') },
                      })
                    }
                    style={({ pressed }) => [styles.expenseCard, pressed && styles.pressed]}>
                    <View style={[styles.smallAvatar, { backgroundColor: `${iconColor}26` }, isDeleted && styles.deletedTile]}>
                      <Icon name={icon} size={18} color={iconColor} />
                    </View>
                    <View style={{ flex: 1, minWidth: 0 }}>
                      <Text style={[styles.expenseDesc, isDeleted && styles.deletedText]} numberOfLines={1}>
                        {ex.description}
                      </Text>
                      <Text style={styles.expenseMeta} numberOfLines={1}>
                        {isDeleted
                          ? ex.deleted_by
                            ? t('groupDetail.deletedBy', { name: ex.deleted_by.name })
                            : t('groupDetail.deletedTag')
                          : t('groupDetail.paidBy', { name: ex.paid_by.name, date: longDate(ex.created_at) })}
                      </Text>
                    </View>
                    <View style={{ alignItems: 'flex-end' }}>
                      <Text style={[styles.expenseAmount, isDeleted && styles.deletedText]}>
                        {formatAmount(ex.amount, group.currency)}
                      </Text>
                      {!isDeleted && paidByMe && lent > 0 ? (
                        <Text style={[styles.expenseShare, { color: Palette.green }]}>
                          {t('groupDetail.youLent', { amount: formatAmount(lent, group.currency) })}
                        </Text>
                      ) : !isDeleted && !paidByMe && myShare > 0 ? (
                        <Text style={[styles.expenseShare, { color: Palette.red }]}>
                          {t('groupDetail.youOwe', { amount: formatAmount(myShare, group.currency) })}
                        </Text>
                      ) : null}
                    </View>
                  </Pressable>
                );

                if (!canDeleteExpense) {
                  return <View key={`e${ex.id}`}>{expenseCard}</View>;
                }

                return (
                  <Swipeable
                    key={`e${ex.id}`}
                    overshootRight={false}
                    renderRightActions={(_progress, _translation, swipeableMethods) => (
                      <Pressable
                        onPress={() => {
                          swipeableMethods.close();
                          setDeletingExpenseId(ex.id);
                        }}
                        style={styles.deleteAction}>
                        <Text style={styles.deleteActionText}>{t('common.delete')}</Text>
                      </Pressable>
                    )}>
                    {expenseCard}
                  </Swipeable>
                );
              })}
              </View>
            </>
          )}

          {tab === 'balances' && (
            <View style={styles.list}>
              {debts.length === 0 ? (
                <View style={styles.settledCard}>
                  <View style={styles.settledCheck}>
                    <Text style={styles.settledCheckText}>✓</Text>
                  </View>
                  <Text style={styles.settledTitle}>{t('groupDetail.allSettled')}</Text>
                  <Text style={styles.settledHint}>{t('groupDetail.allSettledHint')}</Text>
                </View>
              ) : (
                debts.map((d, i) => {
                  // Show the other person's photo — the counterparty relative to me.
                  const otherId =
                    myId != null && d.from_user_id === myId ? d.to_user_id : d.from_user_id;
                  // Only a party to the debt can record it as settled (the backend
                  // enforces this too) — showing the button to bystanders would
                  // just dead-end into a 403.
                  const canSettle = myId != null && (d.from_user_id === myId || d.to_user_id === myId);
                  return (
                  <View key={i} style={styles.balanceCard}>
                    <Avatar
                      uri={memberAvatar(otherId)}
                      name={memberName(otherId)}
                      size={40}
                      color={avatarColor(otherId)}
                      fontSize={15}
                    />
                    <View style={{ flex: 1, minWidth: 0 }}>
                      <Text style={styles.balanceText}>
                        {t('groupDetail.owes', {
                          from: memberName(d.from_user_id),
                          to: memberName(d.to_user_id),
                        })}
                      </Text>
                      <Text style={styles.balanceAmount}>{formatAmount(d.amount, group.currency)}</Text>
                    </View>
                    {canSettle && (
                      <Pressable
                        onPress={() =>
                          router.push({
                            pathname: '/groups/[id]/settle',
                            params: {
                              id: id as string,
                              from: String(d.from_user_id),
                              to: String(d.to_user_id),
                              amount: String(d.amount),
                              currency: group.currency,
                              fromName: memberName(d.from_user_id),
                              toName: memberName(d.to_user_id),
                              fromAvatar: memberAvatar(d.from_user_id),
                              toAvatar: memberAvatar(d.to_user_id),
                            },
                          })
                        }
                        style={styles.settleBtn}>
                        <Text style={styles.settleBtnText}>{t('groupDetail.settle')}</Text>
                      </Pressable>
                    )}
                  </View>
                  );
                })
              )}
            </View>
          )}

          {tab === 'stats' && (
            <View style={styles.statsPanel}>
              <CategoryChart
                slices={categoryBreakdown.slices}
                total={categoryBreakdown.total}
                currency={group.currency}
              />
            </View>
          )}
        </ScrollView>

        {/* FAB */}
        <View style={styles.fabWrap}>
          <Pressable
            onPress={() => router.push(`/groups/${id}/add-expense`)}
            style={({ pressed }) => [styles.fab, pressed && styles.pressed]}>
            <Text style={styles.fabPlus}>+</Text>
            <Text style={styles.fabText}>{t('groupDetail.addExpense')}</Text>
          </Pressable>
        </View>

        {errorMsg && (
          <View style={styles.toast}>
            <Text style={styles.toastDot}>!</Text>
            <Text style={styles.toastText}>{errorMsg}</Text>
          </View>
        )}
      </SafeAreaView>
      <BottomNav active="index" />
      <ConfirmDialog
        visible={deletingSettlementId != null}
        title={t('groupDetail.deleteSettlementTitle')}
        message={t('groupDetail.deleteSettlementMessage')}
        onCancel={() => setDeletingSettlementId(null)}
        onConfirm={confirmDeleteSettlement}
      />
      <ConfirmDialog
        visible={deletingExpenseId != null}
        title={t('expenseDetail.deleteTitle')}
        message={t('expenseDetail.deleteMessage')}
        onCancel={() => setDeletingExpenseId(null)}
        onConfirm={confirmDeleteExpense}
      />
      <EditGroupIconModal
        visible={editingIcon}
        currentEmoji={group.emoji}
        onSelect={saveIcon}
        onCancel={() => setEditingIcon(false)}
      />
      <EditGroupNameModal
        visible={editingName}
        initialName={group.name}
        saving={savingGroup}
        onSave={saveName}
        onCancel={() => setEditingName(false)}
      />

      <FilterSheet
        visible={filtersOpen}
        onClose={() => setFiltersOpen(false)}
        title={t('activity.filters')}
        showClear={activeFilterCount > 0}
        clearLabel={t('activity.clearFilters')}
        onClear={clearFilters}
        doneLabel={t('common.done')}>
        <FilterSection label={t('activity.filterType')}>
          <FilterSegment
            value={filterType}
            onChange={setFilterType}
            options={[
              { value: 'all', label: t('activity.typeAll') },
              { value: 'expense', label: t('activity.typeExpenses') },
              { value: 'settlement', label: t('activity.typePayments') },
            ]}
          />
        </FilterSection>

        <FilterSection label={t('activity.filterPeriod')}>
          <FilterChipRow
            options={(['all', '7d', '30d', '90d'] as PeriodFilter[]).map((v) => ({
              key: v,
              label:
                v === 'all'
                  ? t('activity.periodAll')
                  : v === '7d'
                    ? t('activity.period7d')
                    : v === '30d'
                      ? t('activity.period30d')
                      : t('activity.period90d'),
              active: filterPeriod === v,
              onPress: () => setFilterPeriod(v),
            }))}
          />
        </FilterSection>

        {categoryOptions.length > 0 && (
          <FilterSection label={t('activity.filterCategory')}>
            <FilterChipRow
              options={[
                {
                  key: 'all',
                  label: t('activity.allCategories'),
                  active: filterCategory == null,
                  onPress: () => setFilterCategory(null),
                },
                ...categoryOptions.map(
                  (c): FilterChipOption => ({
                    key: c.slug,
                    label: t(`categories.${c.slug}`),
                    emoji: c.emoji,
                    active: filterCategory === c.slug,
                    onPress: () => setFilterCategory(c.slug),
                  }),
                ),
              ]}
            />
          </FilterSection>
        )}

        {userOptions.length > 1 && (
          <FilterSection label={t('activity.filterPerson')}>
            <FilterChipRow
              options={[
                { key: 'all', label: t('activity.allPeople'), active: filterUserId == null, onPress: () => setFilterUserId(null) },
                ...userOptions.map(
                  (u): FilterChipOption => ({
                    key: String(u.id),
                    label: u.name,
                    active: filterUserId === u.id,
                    onPress: () => setFilterUserId(u.id),
                  }),
                ),
              ]}
            />
          </FilterSection>
        )}
      </FilterSheet>
    </View>
  );
}

const makeStyles = (Palette: ThemeColors) =>
  StyleSheet.create({
  root: { flex: 1, backgroundColor: Palette.bg },
  safe: { flex: 1 },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  muted: { color: Palette.muted, fontSize: 14, fontFamily: Font.sans },
  importCta: {
    marginTop: 12,
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: Radius.pill,
    borderWidth: 1.5,
    borderColor: Palette.cardBorder,
  },
  importCtaText: { fontSize: 13, fontFamily: Font.sansSemibold, color: Palette.ink },
  topbar: {
    paddingHorizontal: 18,
    paddingTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  topActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  iconBtn: {
    width: 38,
    height: 38,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scroll: { paddingTop: 14, paddingBottom: 110 },
  groupHead: { paddingHorizontal: 24, flexDirection: 'row', alignItems: 'center', gap: 13 },
  tile: { width: 52, height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  groupNameWrap: { alignSelf: 'flex-start' },
  groupName: { fontSize: 22, fontFamily: Font.sansBold, letterSpacing: -0.5, color: Palette.ink },
  groupMeta: { marginTop: 3, fontSize: 12.5, color: Palette.muted },
  summary: { marginHorizontal: 24, marginTop: 18, borderRadius: Radius.lg, borderWidth: 1, padding: 16 },
  summaryLabel: { fontSize: 12.5, color: Palette.muted3, fontFamily: Font.sansMedium },
  summaryAmount: { marginTop: 5, fontSize: 24, fontFamily: Font.monoSemibold, letterSpacing: -0.5 },
  summaryWord: { marginTop: 4, fontSize: 12.5, opacity: 0.9 },
  tabs: { flexDirection: 'row', gap: 8, paddingHorizontal: 24, paddingTop: 18 },
  tab: {
    flex: 1,
    height: 38,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Palette.cardBorder,
    backgroundColor: Palette.card,
  },
  tabActive: { backgroundColor: Palette.ink, borderColor: Palette.ink },
  tabText: { fontSize: 13.5, fontFamily: Font.sansSemibold, color: Palette.muted3 },
  tabTextActive: { color: Palette.bg },
  filtersRow: { flexDirection: 'row', justifyContent: 'flex-end', paddingHorizontal: 20, paddingTop: 14 },
  list: { paddingHorizontal: 20, paddingTop: 16, gap: 9 },
  statsPanel: { paddingHorizontal: 24, paddingTop: 20 },
  expenseCard: {
    backgroundColor: Palette.card,
    borderWidth: 1,
    borderColor: Palette.cardBorder,
    borderRadius: 16,
    padding: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
  },
  smallAvatar: { width: 40, height: 40, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  deleteAction: {
    width: 84,
    height: '100%',
    borderRadius: 16,
    backgroundColor: Palette.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deleteActionText: { color: '#fff', fontSize: 13.5, fontFamily: Font.sansSemibold },
  expenseDesc: { fontSize: 14.5, fontFamily: Font.sansSemibold, color: Palette.ink },
  expenseMeta: { marginTop: 3, fontSize: 12, color: Palette.muted },
  expenseAmount: { fontSize: 14, fontFamily: Font.monoSemibold, color: Palette.ink },
  expenseShare: { marginTop: 3, fontSize: 11, color: Palette.muted },
  pendingTag: { marginTop: 3, fontSize: 11, color: Palette.muted, fontStyle: 'italic' },
  deletedTile: { opacity: 0.5 },
  deletedText: { color: Palette.muted, textDecorationLine: 'line-through' },
  balanceCard: {
    backgroundColor: Palette.card,
    borderWidth: 1,
    borderColor: Palette.cardBorder,
    borderRadius: 16,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  balanceText: { fontSize: 13.5, color: Palette.ink, fontFamily: Font.sans },
  balanceAmount: { marginTop: 3, fontSize: 13.5, fontFamily: Font.monoSemibold, color: Palette.ink },
  settleBtn: { backgroundColor: Palette.greenTint, borderRadius: 10, paddingVertical: 8, paddingHorizontal: 13 },
  settleBtnText: { fontSize: 12.5, fontFamily: Font.sansSemibold, color: Palette.green },
  settledCard: {
    backgroundColor: Palette.greenTint,
    borderWidth: 1,
    borderColor: Palette.greenTintBorder,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
  },
  settledCheck: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: Palette.green,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  settledCheckText: { color: '#fff', fontSize: 22 },
  settledTitle: { fontSize: 15, fontFamily: Font.sansSemibold, color: Palette.greenDark },
  settledHint: { marginTop: 4, fontSize: 12.5, color: '#4f7c69' },
  fabWrap: { position: 'absolute', bottom: 26, left: 0, right: 0, alignItems: 'center' },
  fab: {
    height: 54,
    paddingHorizontal: 26,
    borderRadius: Radius.lg,
    backgroundColor: Palette.ink,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  pressed: { opacity: 0.85 },
  fabPlus: { color: Palette.bg, fontSize: 20, lineHeight: 22 },
  fabText: { color: Palette.bg, fontSize: 15, fontFamily: Font.sansSemibold },
  toast: {
    position: 'absolute',
    top: 52,
    alignSelf: 'center',
    maxWidth: '90%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    backgroundColor: Palette.red,
    paddingVertical: 11,
    paddingHorizontal: 15,
    borderRadius: 12,
  },
  toastDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    overflow: 'hidden',
    backgroundColor: '#FFFFFF',
    color: Palette.red,
    fontSize: 12,
    fontFamily: Font.sansBold,
    textAlign: 'center',
    lineHeight: 18,
  },
  toastText: { color: '#FFFFFF', fontSize: 13.5, fontFamily: Font.sansMedium },
});
